<definitions name="PlanChargeFtthSavService" targetNamespace="http://interop-fibre.fr"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://interop-fibre.fr"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:ns1="http://schemas.xmlsoap.org/soap/http">
    <types>
        <xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified"
                   targetNamespace="http://interop-fibre.fr" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="ConsultationRdvRequete">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="idRendezVous" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="RechercheCreneauxLibresRequete">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="typeIntervention" type="tns:typeInterventionType"/>
                        <xs:element name="natureProduit" type="tns:natureProduitType"/>
                        <xs:element name="segmentMarche" type="tns:segmentMarcheType"/>
                        <xs:element minOccurs="0" name="technicalId" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="commercialId" nillable="true" type="xs:string"/>
                        <xs:element name="codeInsee" type="xs:string"/>
                        <xs:element name="dateDebut" type="xs:dateTime"/>
                        <xs:element name="dateFin" type="xs:dateTime"/>
                        <xs:element name="defectPrelocalization" type="tns:defectPrelocalizationType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ReportRDVRequete">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="typeIntervention" type="tns:typeInterventionType"/>
                        <xs:element name="natureProduit" type="tns:natureProduitType"/>
                        <xs:element name="segmentMarche" type="tns:segmentMarcheType"/>
                        <xs:element name="codeInsee" type="xs:string"/>
                        <xs:element name="idRendezvous" type="xs:string"/>
                        <xs:element name="natureReport" type="tns:natureReportType"/>
                        <xs:element name="idCreneau" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ReservationCreneauRequete">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="typeIntervention" type="tns:typeInterventionType"/>
                        <xs:element name="natureProduit" type="tns:natureProduitType"/>
                        <xs:element name="segmentMarche" type="tns:segmentMarcheType"/>
                        <xs:element name="codeInsee" type="xs:string"/>
                        <xs:element name="idCreneau" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="EnteteType">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="versionWS" type="xs:string"/>
                        <xs:element name="horodatageRequete" type="xs:dateTime"/>
                        <xs:element name="horodatageReponse" type="xs:dateTime"/>
                        <xs:element name="sirenOC" type="xs:string"/>
                        <xs:element name="sirenOI" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="RechercheCreneauxLibresReponse">
                <xs:sequence>
                    <xs:element name="codeReponse" type="tns:codeReponseType"/>
                    <xs:element minOccurs="0" name="listeCreneau" nillable="true" type="tns:listeCreneauType"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="InfoErreurType">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="codeErreur" type="xs:int"/>
                        <xs:element name="messageErreur" type="xs:string"/>
                        <xs:element minOccurs="0" name="detailErreur" nillable="true" type="tns:DetailErreurType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="DetailErreurType">
                <xs:sequence>
                    <xs:element name="libelle" type="xs:string"/>
                    <xs:element name="detail" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="listeCreneauType">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="occCreneau" nillable="true"
                                type="tns:CreneauType"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="CreneauType">
                <xs:sequence>
                    <xs:element name="dateDebut" type="xs:dateTime"/>
                    <xs:element name="dateFin" type="xs:dateTime"/>
                    <xs:element name="idOI" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="ConsultationRdvReponse">
                <xs:sequence>
                    <xs:element name="codeReponse" type="tns:codeReponseType"/>
                    <xs:element name="idRendezVous" type="xs:string"/>
                    <xs:element name="dateDebut" type="xs:dateTime"/>
                    <xs:element name="dateFin" type="xs:dateTime"/>
                    <xs:element name="codeInsee" type="xs:int"/>
                    <xs:element name="typeIntervention" type="tns:typeInterventionType"/>
                    <xs:element minOccurs="0" name="natureProduit" nillable="true" type="tns:natureProduitType"/>
                    <xs:element minOccurs="0" name="segmentMarche" nillable="true" type="tns:segmentMarcheType"/>
                    <xs:element name="statutRendezVous" type="tns:statutRendezVousType"/>
                    <xs:element minOccurs="0" name="referencePrestationPrise" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="ReportRDVReponse">
                <xs:sequence>
                    <xs:element name="codeReponse" type="tns:codeReponseType"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="ReservationCreneauReponse">
                <xs:sequence>
                    <xs:element name="codeReponse" type="tns:codeReponseType"/>
                    <xs:element minOccurs="0" name="idRendezvous" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="typeInterventionType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="P"/>
                    <xs:enumeration value="S"/>
                    <xs:enumeration value="E"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="natureProduitType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="FTTH_ACCES"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="segmentMarcheType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ENTREPRISE"/>
                    <xs:enumeration value="GP"/>
                    <xs:enumeration value="OPERATEUR"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="defectPrelocalizationType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="PTO"/>
                    <xs:enumeration value="RACCO PALIER"/>
                    <xs:enumeration value="PBO"/>
                    <xs:enumeration value="PM-PBO"/>
                    <xs:enumeration value="PM"/>
                    <xs:enumeration value="HORIZONTALE RESEAU"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="codeReponseType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="OK"/>
                    <xs:enumeration value="KO"/>
                    <xs:enumeration value="NA"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="statutRendezVousType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="CREE"/>
                    <xs:enumeration value="CONFIRME"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="natureReportType">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="REPORT_RDV_RESERVE"/>
                    <xs:enumeration value="REPORT_RDV_CONFIRME"/>
                    <xs:enumeration value="NOUVEAU_RDV"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="RechercheCreneauxLibresReponse" nillable="true"
                        type="tns:RechercheCreneauxLibresReponse"/>
            <xs:element name="ConsultationRdvReponse" nillable="true" type="tns:ConsultationRdvReponse"/>
            <xs:element name="ReportRDVReponse" nillable="true" type="tns:ReportRDVReponse"/>
            <xs:element name="ReservationCreneauReponse" nillable="true" type="tns:ReservationCreneauReponse"/>
        </xs:schema>
    </types>
    <message name="reportRDVResponse">
        <part element="tns:ReportRDVReponse" name="ReportRDVReponse"/>
    </message>
    <message name="reportRDV">
        <part element="tns:ReportRDVRequete" name="parameters"/>
    </message>
    <message name="reservationCreneau">
        <part element="tns:ReservationCreneauRequete" name="parameters"/>
    </message>
    <message name="reservationCreneauResponse">
        <part element="tns:ReservationCreneauReponse" name="ReservationCreneauReponse"/>
    </message>
    <message name="rechercheCreneauxLibresResponse">
        <part element="tns:RechercheCreneauxLibresReponse" name="RechercheCreneauxLibresReponse"/>
    </message>
    <message name="rechercheCreneauxLibres">
        <part element="tns:RechercheCreneauxLibresRequete" name="parameters"/>
    </message>
    <message name="consultationRdvResponse">
        <part element="tns:ConsultationRdvReponse" name="ConsultationRdvReponse"/>
    </message>
    <message name="consultationRdv">
        <part element="tns:ConsultationRdvRequete" name="parameters"/>
    </message>
    <message name="InfoErreurTypeMessage">
        <part name="fault" element="tns:InfoErreurType"/>
    </message>
    <message name="EnteteTypeMessage">
        <part name="EnteteType" element="tns:EnteteType"/>
    </message>
    <portType name="PlanChargeFtthSav">
        <operation name="rechercheCreneauxLibres">
            <input message="tns:rechercheCreneauxLibres" name="rechercheCreneauxLibres"/>
            <output message="tns:rechercheCreneauxLibresResponse" name="rechercheCreneauxLibresResponse"/>
            <fault message="tns:InfoErreurTypeMessage" name="rdvErreur"/>
        </operation>
        <operation name="consultationRdv">
            <input message="tns:consultationRdv" name="consultationRdv"/>
            <output message="tns:consultationRdvResponse" name="consultationRdvResponse"/>
            <fault message="tns:InfoErreurTypeMessage" name="rdvErreur"/>
        </operation>
        <operation name="reportRDV">
            <input message="tns:reportRDV" name="reportRDV"/>
            <output message="tns:reportRDVResponse" name="reportRDVResponse"/>
            <fault message="tns:InfoErreurTypeMessage" name="rdvErreur"/>
        </operation>
        <operation name="reservationCreneau">
            <input message="tns:reservationCreneau" name="reservationCreneau"/>
            <output message="tns:reservationCreneauResponse" name="reservationCreneauResponse"/>
            <fault message="tns:InfoErreurTypeMessage" name="rdvErreur"/>
        </operation>
    </portType>
    <binding name="PlanChargeFtthSavServiceSoapBinding" type="tns:PlanChargeFtthSav">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="rechercheCreneauxLibres">
            <soap:operation soapAction="" style="document"/>
            <input name="rechercheCreneauxLibres">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </input>
            <output name="rechercheCreneauxLibresResponse">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </output>
            <fault name="rdvErreur">
                <soap:fault name="rdvErreur" use="literal"/>
            </fault>
        </operation>
        <operation name="consultationRdv">
            <soap:operation soapAction="" style="document"/>
            <input name="consultationRdv">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </input>
            <output name="consultationRdvResponse">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </output>
            <fault name="rdvErreur">
                <soap:fault name="rdvErreur" use="literal"/>
            </fault>
        </operation>
        <operation name="reportRDV">
            <soap:operation soapAction="" style="document"/>
            <input name="reportRDV">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </input>
            <output name="reportRDVResponse">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </output>
            <fault name="rdvErreur">
                <soap:fault name="rdvErreur" use="literal"/>
            </fault>
        </operation>
        <operation name="reservationCreneau">
            <soap:operation soapAction="" style="document"/>
            <input name="reservationCreneau">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </input>
            <output name="reservationCreneauResponse">
                <soap:body use="literal"/>
                <soap:header message="tns:EnteteTypeMessage" part="EnteteType"/>
            </output>
            <fault name="rdvErreur">
                <soap:fault name="rdvErreur" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="PlanChargeFtthSavService">
        <port binding="tns:PlanChargeFtthSavServiceSoapBinding" name="PlanChargeFtthSavPort">
            <soap:address location="http://localhost:8080/sav-ftth/services/rdvFtthSav"/>
        </port>
    </service>
</definitions>
