
package fr.interop_fibre;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InfoErreurType", targetNamespace = "http://interop-fibre.fr")
public class InfoErreurTypeMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InfoErreurType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InfoErreurTypeMessage(String message, InfoErreurType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InfoErreurTypeMessage(String message, InfoErreurType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.interop_fibre.InfoErreurType
     */
    public InfoErreurType getFaultInfo() {
        return faultInfo;
    }

}
