
package fr.interop_fibre;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlanChargeFtthSavService", targetNamespace = "http://interop-fibre.fr", wsdlLocation = "file:/home/jlesaux/workspace/plandechargesav/planChargeSavFtth.wsdl")
public class PlanChargeFtthSavService
    extends Service
{

    private final static URL PLANCHARGEFTTHSAVSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLANCHARGEFTTHSAVSERVICE_EXCEPTION;
    private final static QName PLANCHARGEFTTHSAVSERVICE_QNAME = new QName("http://interop-fibre.fr", "PlanChargeFtthSavService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jlesaux/workspace/plandechargesav/planChargeSavFtth.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLANCHARGEFTTHSAVSERVICE_WSDL_LOCATION = url;
        PLANCHARGEFTTHSAVSERVICE_EXCEPTION = e;
    }

    public PlanChargeFtthSavService() {
        super(__getWsdlLocation(), PLANCHARGEFTTHSAVSERVICE_QNAME);
    }

    public PlanChargeFtthSavService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLANCHARGEFTTHSAVSERVICE_QNAME, features);
    }

    public PlanChargeFtthSavService(URL wsdlLocation) {
        super(wsdlLocation, PLANCHARGEFTTHSAVSERVICE_QNAME);
    }

    public PlanChargeFtthSavService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLANCHARGEFTTHSAVSERVICE_QNAME, features);
    }

    public PlanChargeFtthSavService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanChargeFtthSavService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlanChargeFtthSav
     */
    @WebEndpoint(name = "PlanChargeFtthSavPort")
    public PlanChargeFtthSav getPlanChargeFtthSavPort() {
        return super.getPort(new QName("http://interop-fibre.fr", "PlanChargeFtthSavPort"), PlanChargeFtthSav.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanChargeFtthSav
     */
    @WebEndpoint(name = "PlanChargeFtthSavPort")
    public PlanChargeFtthSav getPlanChargeFtthSavPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interop-fibre.fr", "PlanChargeFtthSavPort"), PlanChargeFtthSav.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLANCHARGEFTTHSAVSERVICE_EXCEPTION!= null) {
            throw PLANCHARGEFTTHSAVSERVICE_EXCEPTION;
        }
        return PLANCHARGEFTTHSAVSERVICE_WSDL_LOCATION;
    }

}
