
package fr.interop_fibre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlanChargeFtthSav", targetNamespace = "http://interop-fibre.fr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlanChargeFtthSav {


    /**
     * 
     * @param parameters
     * @return
     *     returns fr.interop_fibre.RechercheCreneauxLibresReponse
     * @throws InfoErreurTypeMessage
     */
    @WebMethod
    @WebResult(name = "RechercheCreneauxLibresReponse", targetNamespace = "http://interop-fibre.fr", partName = "RechercheCreneauxLibresReponse")
    public RechercheCreneauxLibresReponse rechercheCreneauxLibres(
        @WebParam(name = "RechercheCreneauxLibresRequete", targetNamespace = "http://interop-fibre.fr", partName = "parameters")
        RechercheCreneauxLibresRequete parameters)
        throws InfoErreurTypeMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns fr.interop_fibre.ConsultationRdvReponse
     * @throws InfoErreurTypeMessage
     */
    @WebMethod
    @WebResult(name = "ConsultationRdvReponse", targetNamespace = "http://interop-fibre.fr", partName = "ConsultationRdvReponse")
    public ConsultationRdvReponse consultationRdv(
        @WebParam(name = "ConsultationRdvRequete", targetNamespace = "http://interop-fibre.fr", partName = "parameters")
        ConsultationRdvRequete parameters)
        throws InfoErreurTypeMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns fr.interop_fibre.ReportRDVReponse
     * @throws InfoErreurTypeMessage
     */
    @WebMethod
    @WebResult(name = "ReportRDVReponse", targetNamespace = "http://interop-fibre.fr", partName = "ReportRDVReponse")
    public ReportRDVReponse reportRDV(
        @WebParam(name = "ReportRDVRequete", targetNamespace = "http://interop-fibre.fr", partName = "parameters")
        ReportRDVRequete parameters)
        throws InfoErreurTypeMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns fr.interop_fibre.ReservationCreneauReponse
     * @throws InfoErreurTypeMessage
     */
    @WebMethod
    @WebResult(name = "ReservationCreneauReponse", targetNamespace = "http://interop-fibre.fr", partName = "ReservationCreneauReponse")
    public ReservationCreneauReponse reservationCreneau(
        @WebParam(name = "ReservationCreneauRequete", targetNamespace = "http://interop-fibre.fr", partName = "parameters")
        ReservationCreneauRequete parameters)
        throws InfoErreurTypeMessage
    ;

}
